import { Dimensions } from 'react-native'

const Constants = {
    APP_NAME: 'ShueApp',
    colors: {
        primary: '#000000',
        primaryLight: '#1BECCF',
        textColor: '#CEA245',
        background: '#FBFBFB',
        secondary: '#CCA145',
        peru: '#CCA145',
        white: '#ffffff',
        dirtBrown: '#7C6335',
        mutedText: 'rgba(137,128,128,0.89)',
        grayText: 'rgba(102, 102, 102, 1)',
        facebook: '#4267B2',
        googlePlus: '#db4a39',
        red: '#ff1600',
        selected: '#FFFFFF',
        black: '#000000',
        transparent: 'transparent',
        blackFaded: 'rgb(106,105,105)',
        lightgray: 'lightgray',
        lightGray: 'lightgray',
        warning: '#F3A540',
        lightCyan: '#1FABA7',
        danger: '#F73E3E',
        grayBg: '#F5F5F5',
        dividerDark: '#1d1d1d',
        border: '#c7bdbd',
        invertBackground: '#F9F9F9',
        newsDescription: '#7E7373',
        clock: '#213C45',
        inputBg: '#F5F5F5',
        green: 'green',
    },
    fontFamily: {
        RobotoBold: 'Roboto-Bold',
        RobotoRegular: 'Roboto-Regular',
        RobotoLight: 'Roboto-Light',
        PoppinsSemiBold: 'Poppins-SemiBold',
        PoppinsBold: 'Poppins-Bold',
        PoppinsLight: 'Poppins-Light',
        PoppinsRegular: 'Poppins-Regular',
        PoppinsMedium: 'Poppins-Medium',
    },
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
    padding: 16,
    margin: 16,
    borderRadius: 6,
}
export default Constants